#if PLAYMAKER
using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;
using HutongGames.PlayMaker.Actions;
using HutongGames.PlayMaker;
using UnityEngine;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's id")]
public partial class itemGetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5047456246322143149UL,8980686484588277650UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5268413024771728527UL, 3739230893231629464UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5156247584957195160UL, 10308371707207658898UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_attack;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___attack => _ufle12jhs77_attack ?? (_ufle12jhs77_attack = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4710289117348944613UL, 11650379089385736347UL), () => _ufle12jhs77_attack = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_sprite;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite __generatedField___sprite => _ufle12jhs77_sprite ?? (_ufle12jhs77_sprite = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5022131809095265803UL, 728595562038954171UL), () => _ufle12jhs77_sprite = null));
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_prefab;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab __generatedField___prefab => _ufle12jhs77_prefab ?? (_ufle12jhs77_prefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(MetaDefault, new BGId(5630867991450139845UL, 6075056788782858112UL), () => _ufle12jhs77_prefab = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_available;
	public static BansheeGz.BGDatabase.BGFieldBool __generatedField___available => _ufle12jhs77_available ?? (_ufle12jhs77_available = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5176647130176935201UL, 5981157760426475428UL), () => _ufle12jhs77_available = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmInt name_text;
	[UIHint(UIHint.Variable)]
	public FsmInt attack;
	[UIHint(UIHint.Variable)]
	[ObjectType(typeof(UnityEngine.Sprite))]
	public FsmObject sprite;
	[UIHint(UIHint.Variable)]
	public FsmGameObject prefab;
	[UIHint(UIHint.Variable)]
	public FsmBool available;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		name = null;
		name_text = null;
		attack = null;
		sprite = null;
		prefab = null;
		available = null;
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!name_text.IsNone)
		{
			name_text.Value = __generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!attack.IsNone)
		{
			attack.Value = __generatedField___attack[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!sprite.IsNone)
		{
			sprite.Value = __generatedField___sprite[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!prefab.IsNone)
		{
			prefab.Value = __generatedField___prefab[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!available.IsNone)
		{
			available.Value = __generatedField___available[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's id")]
public partial class itemSetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5047456246322143149UL,8980686484588277650UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5268413024771728527UL, 3739230893231629464UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5156247584957195160UL, 10308371707207658898UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_attack;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___attack => _ufle12jhs77_attack ?? (_ufle12jhs77_attack = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4710289117348944613UL, 11650379089385736347UL), () => _ufle12jhs77_attack = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_available;
	public static BansheeGz.BGDatabase.BGFieldBool __generatedField___available => _ufle12jhs77_available ?? (_ufle12jhs77_available = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5176647130176935201UL, 5981157760426475428UL), () => _ufle12jhs77_available = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	public FsmString name;
	public FsmInt name_text;
	public FsmInt attack;
	public FsmBool available;
	public override void Reset()
	{
		name = null;
		name_text = null;
		attack = null;
		available = null;
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, id=" + as_dfa_fghsafa475_fasdfr3wetjr_id);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!name_text.IsNone)
		{
			__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
		}
		if(!attack.IsNone)
		{
			__generatedField___attack[as_dfa_fghsafa475_fasdfr3wetjr_index] = attack.Value;
		}
		if(!available.IsNone)
		{
			__generatedField___available[as_dfa_fghsafa475_fasdfr3wetjr_index] = available.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's index")]
public partial class itemGetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5047456246322143149UL,8980686484588277650UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5268413024771728527UL, 3739230893231629464UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5156247584957195160UL, 10308371707207658898UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_attack;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___attack => _ufle12jhs77_attack ?? (_ufle12jhs77_attack = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4710289117348944613UL, 11650379089385736347UL), () => _ufle12jhs77_attack = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_sprite;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite __generatedField___sprite => _ufle12jhs77_sprite ?? (_ufle12jhs77_sprite = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5022131809095265803UL, 728595562038954171UL), () => _ufle12jhs77_sprite = null));
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_prefab;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab __generatedField___prefab => _ufle12jhs77_prefab ?? (_ufle12jhs77_prefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(MetaDefault, new BGId(5630867991450139845UL, 6075056788782858112UL), () => _ufle12jhs77_prefab = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_available;
	public static BansheeGz.BGDatabase.BGFieldBool __generatedField___available => _ufle12jhs77_available ?? (_ufle12jhs77_available = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5176647130176935201UL, 5981157760426475428UL), () => _ufle12jhs77_available = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmInt name_text;
	[UIHint(UIHint.Variable)]
	public FsmInt attack;
	[UIHint(UIHint.Variable)]
	[ObjectType(typeof(UnityEngine.Sprite))]
	public FsmObject sprite;
	[UIHint(UIHint.Variable)]
	public FsmGameObject prefab;
	[UIHint(UIHint.Variable)]
	public FsmBool available;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		name = null;
		name_text = null;
		attack = null;
		sprite = null;
		prefab = null;
		available = null;
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = MetaDefault.GetEntity(as_dfa_fghsafa475_fasdfr3wetjr_index).Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!name_text.IsNone)
		{
			name_text.Value = __generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!attack.IsNone)
		{
			attack.Value = __generatedField___attack[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!sprite.IsNone)
		{
			sprite.Value = __generatedField___sprite[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!prefab.IsNone)
		{
			prefab.Value = __generatedField___prefab[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!available.IsNone)
		{
			available.Value = __generatedField___available[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's index")]
public partial class itemSetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5047456246322143149UL,8980686484588277650UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5268413024771728527UL, 3739230893231629464UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5156247584957195160UL, 10308371707207658898UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_attack;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___attack => _ufle12jhs77_attack ?? (_ufle12jhs77_attack = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4710289117348944613UL, 11650379089385736347UL), () => _ufle12jhs77_attack = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_available;
	public static BansheeGz.BGDatabase.BGFieldBool __generatedField___available => _ufle12jhs77_available ?? (_ufle12jhs77_available = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5176647130176935201UL, 5981157760426475428UL), () => _ufle12jhs77_available = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public FsmString name;
	public FsmInt name_text;
	public FsmInt attack;
	public FsmBool available;
	public override void Reset()
	{
		name = null;
		name_text = null;
		attack = null;
		available = null;
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Finish();
			return;
		}
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!name_text.IsNone)
		{
			__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
		}
		if(!attack.IsNone)
		{
			__generatedField___attack[as_dfa_fghsafa475_fasdfr3wetjr_index] = attack.Value;
		}
		if(!available.IsNone)
		{
			__generatedField___available[as_dfa_fghsafa475_fasdfr3wetjr_index] = available.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's name")]
public partial class itemGetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5047456246322143149UL,8980686484588277650UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5268413024771728527UL, 3739230893231629464UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5156247584957195160UL, 10308371707207658898UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_attack;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___attack => _ufle12jhs77_attack ?? (_ufle12jhs77_attack = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4710289117348944613UL, 11650379089385736347UL), () => _ufle12jhs77_attack = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_sprite;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite __generatedField___sprite => _ufle12jhs77_sprite ?? (_ufle12jhs77_sprite = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5022131809095265803UL, 728595562038954171UL), () => _ufle12jhs77_sprite = null));
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_prefab;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab __generatedField___prefab => _ufle12jhs77_prefab ?? (_ufle12jhs77_prefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(MetaDefault, new BGId(5630867991450139845UL, 6075056788782858112UL), () => _ufle12jhs77_prefab = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_available;
	public static BansheeGz.BGDatabase.BGFieldBool __generatedField___available => _ufle12jhs77_available ?? (_ufle12jhs77_available = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5176647130176935201UL, 5981157760426475428UL), () => _ufle12jhs77_available = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmInt name_text;
	[UIHint(UIHint.Variable)]
	public FsmInt attack;
	[UIHint(UIHint.Variable)]
	[ObjectType(typeof(UnityEngine.Sprite))]
	public FsmObject sprite;
	[UIHint(UIHint.Variable)]
	public FsmGameObject prefab;
	[UIHint(UIHint.Variable)]
	public FsmBool available;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Name=null;
		name = null;
		name_text = null;
		attack = null;
		sprite = null;
		prefab = null;
		available = null;
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("item");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=item");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = entity.Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!name_text.IsNone)
		{
			name_text.Value = __generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!attack.IsNone)
		{
			attack.Value = __generatedField___attack[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!sprite.IsNone)
		{
			sprite.Value = __generatedField___sprite[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!prefab.IsNone)
		{
			prefab.Value = __generatedField___prefab[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!available.IsNone)
		{
			available.Value = __generatedField___available[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's name")]
public partial class itemSetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5047456246322143149UL,8980686484588277650UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5268413024771728527UL, 3739230893231629464UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5156247584957195160UL, 10308371707207658898UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_attack;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___attack => _ufle12jhs77_attack ?? (_ufle12jhs77_attack = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4710289117348944613UL, 11650379089385736347UL), () => _ufle12jhs77_attack = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_available;
	public static BansheeGz.BGDatabase.BGFieldBool __generatedField___available => _ufle12jhs77_available ?? (_ufle12jhs77_available = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5176647130176935201UL, 5981157760426475428UL), () => _ufle12jhs77_available = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	public FsmString name;
	public FsmInt name_text;
	public FsmInt attack;
	public FsmBool available;
	public override void Reset()
	{
		_Name=null;
		name = null;
		name_text = null;
		attack = null;
		available = null;
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("item");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=item");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, name=" + _Name.Value);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!name_text.IsNone)
		{
			__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
		}
		if(!attack.IsNone)
		{
			__generatedField___attack[as_dfa_fghsafa475_fasdfr3wetjr_index] = attack.Value;
		}
		if(!available.IsNone)
		{
			__generatedField___available[as_dfa_fghsafa475_fasdfr3wetjr_index] = available.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Get the number of rows for item meta")]
public partial class itemCount : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5047456246322143149UL,8980686484588277650UL), () => _metaDefault = null));
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entities count")]
	public FsmInt Count;
	public override void OnEnter()
	{
		if(Count != null)
		{
			Count.Value = MetaDefault.CountEntities;
		}
		Finish();
	}
	public override void Reset() => Count = null;
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Create new row")]
public partial class itemCreate : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5047456246322143149UL,8980686484588277650UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5268413024771728527UL, 3739230893231629464UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5156247584957195160UL, 10308371707207658898UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_attack;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___attack => _ufle12jhs77_attack ?? (_ufle12jhs77_attack = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4710289117348944613UL, 11650379089385736347UL), () => _ufle12jhs77_attack = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_available;
	public static BansheeGz.BGDatabase.BGFieldBool __generatedField___available => _ufle12jhs77_available ?? (_ufle12jhs77_available = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5176647130176935201UL, 5981157760426475428UL), () => _ufle12jhs77_available = null));
	public FsmString name;
	public FsmInt name_text;
	public FsmInt attack;
	public FsmBool available;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void Reset()
	{
		name = null;
		name_text = null;
		attack = null;
		available = null;
	}
	public override void OnEnter()
	{
		MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(___e => {
			var as_dfa_fghsafa475_fasdfr3wetjr_index = ___e.Index;
			if(!_Index.IsNone)
			{
				_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
			}
			if(!name.IsNone)
			{
				__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
			}
			if(!name_text.IsNone)
			{
				__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
			}
			if(!attack.IsNone)
			{
				__generatedField___attack[as_dfa_fghsafa475_fasdfr3wetjr_index] = attack.Value;
			}
			if(!available.IsNone)
			{
				__generatedField___available[as_dfa_fghsafa475_fasdfr3wetjr_index] = available.Value;
			}
		}));
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Delete the row by its index for item meta")]
public partial class itemDelete : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5047456246322143149UL,8980686484588277650UL), () => _metaDefault = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		if (_Index.Value < 0)
		{
			Debug.LogWarning("Unable to delete, index is less than zero: " + _Index.Value);
			Finish();
			return;
		}
		if (_Index.Value >= MetaDefault.CountEntities)
		{
			Debug.LogWarning("Unable to delete, index is equal or greater than number of rows: " + _Index.Value +">=" + MetaDefault.CountEntities);
			Finish();
			return;
		}
		var entity = MetaDefault.GetEntity(_Index.Value);
		entity.Delete();
		Finish();
	}
	public override void Reset() => _Index = null;
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's id")]
public partial class STRINGGetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5631677311434746689UL,4032041762606905268UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4788250445857267899UL, 12469065357673099440UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_TW;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___TW => _ufle12jhs77_TW ?? (_ufle12jhs77_TW = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5350824339626827415UL, 4806768780051820706UL), () => _ufle12jhs77_TW = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_EN;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___EN => _ufle12jhs77_EN ?? (_ufle12jhs77_EN = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5104490657888741800UL, 15143247162242646201UL), () => _ufle12jhs77_EN = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_JP;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___JP => _ufle12jhs77_JP ?? (_ufle12jhs77_JP = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4923137236680500196UL, 9891204786024099255UL), () => _ufle12jhs77_JP = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmString TW;
	[UIHint(UIHint.Variable)]
	public FsmString EN;
	[UIHint(UIHint.Variable)]
	public FsmString JP;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		name = null;
		TW = null;
		EN = null;
		JP = null;
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!TW.IsNone)
		{
			TW.Value = __generatedField___TW[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!EN.IsNone)
		{
			EN.Value = __generatedField___EN[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!JP.IsNone)
		{
			JP.Value = __generatedField___JP[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's id")]
public partial class STRINGSetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5631677311434746689UL,4032041762606905268UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4788250445857267899UL, 12469065357673099440UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_TW;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___TW => _ufle12jhs77_TW ?? (_ufle12jhs77_TW = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5350824339626827415UL, 4806768780051820706UL), () => _ufle12jhs77_TW = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_EN;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___EN => _ufle12jhs77_EN ?? (_ufle12jhs77_EN = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5104490657888741800UL, 15143247162242646201UL), () => _ufle12jhs77_EN = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_JP;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___JP => _ufle12jhs77_JP ?? (_ufle12jhs77_JP = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4923137236680500196UL, 9891204786024099255UL), () => _ufle12jhs77_JP = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	public FsmString name;
	public FsmString TW;
	public FsmString EN;
	public FsmString JP;
	public override void Reset()
	{
		name = null;
		TW = null;
		EN = null;
		JP = null;
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, id=" + as_dfa_fghsafa475_fasdfr3wetjr_id);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!TW.IsNone)
		{
			__generatedField___TW[as_dfa_fghsafa475_fasdfr3wetjr_index] = TW.Value;
		}
		if(!EN.IsNone)
		{
			__generatedField___EN[as_dfa_fghsafa475_fasdfr3wetjr_index] = EN.Value;
		}
		if(!JP.IsNone)
		{
			__generatedField___JP[as_dfa_fghsafa475_fasdfr3wetjr_index] = JP.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's index")]
public partial class STRINGGetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5631677311434746689UL,4032041762606905268UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4788250445857267899UL, 12469065357673099440UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_TW;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___TW => _ufle12jhs77_TW ?? (_ufle12jhs77_TW = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5350824339626827415UL, 4806768780051820706UL), () => _ufle12jhs77_TW = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_EN;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___EN => _ufle12jhs77_EN ?? (_ufle12jhs77_EN = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5104490657888741800UL, 15143247162242646201UL), () => _ufle12jhs77_EN = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_JP;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___JP => _ufle12jhs77_JP ?? (_ufle12jhs77_JP = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4923137236680500196UL, 9891204786024099255UL), () => _ufle12jhs77_JP = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmString TW;
	[UIHint(UIHint.Variable)]
	public FsmString EN;
	[UIHint(UIHint.Variable)]
	public FsmString JP;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		name = null;
		TW = null;
		EN = null;
		JP = null;
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = MetaDefault.GetEntity(as_dfa_fghsafa475_fasdfr3wetjr_index).Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!TW.IsNone)
		{
			TW.Value = __generatedField___TW[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!EN.IsNone)
		{
			EN.Value = __generatedField___EN[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!JP.IsNone)
		{
			JP.Value = __generatedField___JP[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's index")]
public partial class STRINGSetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5631677311434746689UL,4032041762606905268UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4788250445857267899UL, 12469065357673099440UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_TW;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___TW => _ufle12jhs77_TW ?? (_ufle12jhs77_TW = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5350824339626827415UL, 4806768780051820706UL), () => _ufle12jhs77_TW = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_EN;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___EN => _ufle12jhs77_EN ?? (_ufle12jhs77_EN = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5104490657888741800UL, 15143247162242646201UL), () => _ufle12jhs77_EN = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_JP;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___JP => _ufle12jhs77_JP ?? (_ufle12jhs77_JP = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4923137236680500196UL, 9891204786024099255UL), () => _ufle12jhs77_JP = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public FsmString name;
	public FsmString TW;
	public FsmString EN;
	public FsmString JP;
	public override void Reset()
	{
		name = null;
		TW = null;
		EN = null;
		JP = null;
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Finish();
			return;
		}
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!TW.IsNone)
		{
			__generatedField___TW[as_dfa_fghsafa475_fasdfr3wetjr_index] = TW.Value;
		}
		if(!EN.IsNone)
		{
			__generatedField___EN[as_dfa_fghsafa475_fasdfr3wetjr_index] = EN.Value;
		}
		if(!JP.IsNone)
		{
			__generatedField___JP[as_dfa_fghsafa475_fasdfr3wetjr_index] = JP.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's name")]
public partial class STRINGGetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5631677311434746689UL,4032041762606905268UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4788250445857267899UL, 12469065357673099440UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_TW;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___TW => _ufle12jhs77_TW ?? (_ufle12jhs77_TW = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5350824339626827415UL, 4806768780051820706UL), () => _ufle12jhs77_TW = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_EN;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___EN => _ufle12jhs77_EN ?? (_ufle12jhs77_EN = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5104490657888741800UL, 15143247162242646201UL), () => _ufle12jhs77_EN = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_JP;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___JP => _ufle12jhs77_JP ?? (_ufle12jhs77_JP = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4923137236680500196UL, 9891204786024099255UL), () => _ufle12jhs77_JP = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmString TW;
	[UIHint(UIHint.Variable)]
	public FsmString EN;
	[UIHint(UIHint.Variable)]
	public FsmString JP;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Name=null;
		name = null;
		TW = null;
		EN = null;
		JP = null;
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("STRING");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=STRING");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = entity.Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!TW.IsNone)
		{
			TW.Value = __generatedField___TW[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!EN.IsNone)
		{
			EN.Value = __generatedField___EN[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!JP.IsNone)
		{
			JP.Value = __generatedField___JP[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's name")]
public partial class STRINGSetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5631677311434746689UL,4032041762606905268UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4788250445857267899UL, 12469065357673099440UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_TW;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___TW => _ufle12jhs77_TW ?? (_ufle12jhs77_TW = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5350824339626827415UL, 4806768780051820706UL), () => _ufle12jhs77_TW = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_EN;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___EN => _ufle12jhs77_EN ?? (_ufle12jhs77_EN = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5104490657888741800UL, 15143247162242646201UL), () => _ufle12jhs77_EN = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_JP;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___JP => _ufle12jhs77_JP ?? (_ufle12jhs77_JP = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4923137236680500196UL, 9891204786024099255UL), () => _ufle12jhs77_JP = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	public FsmString name;
	public FsmString TW;
	public FsmString EN;
	public FsmString JP;
	public override void Reset()
	{
		_Name=null;
		name = null;
		TW = null;
		EN = null;
		JP = null;
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("STRING");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=STRING");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, name=" + _Name.Value);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!TW.IsNone)
		{
			__generatedField___TW[as_dfa_fghsafa475_fasdfr3wetjr_index] = TW.Value;
		}
		if(!EN.IsNone)
		{
			__generatedField___EN[as_dfa_fghsafa475_fasdfr3wetjr_index] = EN.Value;
		}
		if(!JP.IsNone)
		{
			__generatedField___JP[as_dfa_fghsafa475_fasdfr3wetjr_index] = JP.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Get the number of rows for STRING meta")]
public partial class STRINGCount : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5631677311434746689UL,4032041762606905268UL), () => _metaDefault = null));
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entities count")]
	public FsmInt Count;
	public override void OnEnter()
	{
		if(Count != null)
		{
			Count.Value = MetaDefault.CountEntities;
		}
		Finish();
	}
	public override void Reset() => Count = null;
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Create new row")]
public partial class STRINGCreate : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5631677311434746689UL,4032041762606905268UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4788250445857267899UL, 12469065357673099440UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_TW;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___TW => _ufle12jhs77_TW ?? (_ufle12jhs77_TW = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5350824339626827415UL, 4806768780051820706UL), () => _ufle12jhs77_TW = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_EN;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___EN => _ufle12jhs77_EN ?? (_ufle12jhs77_EN = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5104490657888741800UL, 15143247162242646201UL), () => _ufle12jhs77_EN = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_JP;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___JP => _ufle12jhs77_JP ?? (_ufle12jhs77_JP = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4923137236680500196UL, 9891204786024099255UL), () => _ufle12jhs77_JP = null));
	public FsmString name;
	public FsmString TW;
	public FsmString EN;
	public FsmString JP;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void Reset()
	{
		name = null;
		TW = null;
		EN = null;
		JP = null;
	}
	public override void OnEnter()
	{
		MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(___e => {
			var as_dfa_fghsafa475_fasdfr3wetjr_index = ___e.Index;
			if(!_Index.IsNone)
			{
				_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
			}
			if(!name.IsNone)
			{
				__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
			}
			if(!TW.IsNone)
			{
				__generatedField___TW[as_dfa_fghsafa475_fasdfr3wetjr_index] = TW.Value;
			}
			if(!EN.IsNone)
			{
				__generatedField___EN[as_dfa_fghsafa475_fasdfr3wetjr_index] = EN.Value;
			}
			if(!JP.IsNone)
			{
				__generatedField___JP[as_dfa_fghsafa475_fasdfr3wetjr_index] = JP.Value;
			}
		}));
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Delete the row by its index for STRING meta")]
public partial class STRINGDelete : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5631677311434746689UL,4032041762606905268UL), () => _metaDefault = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		if (_Index.Value < 0)
		{
			Debug.LogWarning("Unable to delete, index is less than zero: " + _Index.Value);
			Finish();
			return;
		}
		if (_Index.Value >= MetaDefault.CountEntities)
		{
			Debug.LogWarning("Unable to delete, index is equal or greater than number of rows: " + _Index.Value +">=" + MetaDefault.CountEntities);
			Finish();
			return;
		}
		var entity = MetaDefault.GetEntity(_Index.Value);
		entity.Delete();
		Finish();
	}
	public override void Reset() => _Index = null;
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's id")]
public partial class BACKPACKGetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4747402433082010641UL,7921280683061573257UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5286057603126314049UL, 5927070171552478377UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_item_count;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___item_count => _ufle12jhs77_item_count ?? (_ufle12jhs77_item_count = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4880672858270195464UL, 2402488877140250532UL), () => _ufle12jhs77_item_count = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmInt item_count;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		name = null;
		item_count = null;
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!item_count.IsNone)
		{
			item_count.Value = __generatedField___item_count[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's id")]
public partial class BACKPACKSetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4747402433082010641UL,7921280683061573257UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5286057603126314049UL, 5927070171552478377UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_item_count;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___item_count => _ufle12jhs77_item_count ?? (_ufle12jhs77_item_count = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4880672858270195464UL, 2402488877140250532UL), () => _ufle12jhs77_item_count = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	public FsmString name;
	public FsmInt item_count;
	public override void Reset()
	{
		name = null;
		item_count = null;
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, id=" + as_dfa_fghsafa475_fasdfr3wetjr_id);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!item_count.IsNone)
		{
			__generatedField___item_count[as_dfa_fghsafa475_fasdfr3wetjr_index] = item_count.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's index")]
public partial class BACKPACKGetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4747402433082010641UL,7921280683061573257UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5286057603126314049UL, 5927070171552478377UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_item_count;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___item_count => _ufle12jhs77_item_count ?? (_ufle12jhs77_item_count = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4880672858270195464UL, 2402488877140250532UL), () => _ufle12jhs77_item_count = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmInt item_count;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		name = null;
		item_count = null;
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = MetaDefault.GetEntity(as_dfa_fghsafa475_fasdfr3wetjr_index).Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!item_count.IsNone)
		{
			item_count.Value = __generatedField___item_count[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's index")]
public partial class BACKPACKSetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4747402433082010641UL,7921280683061573257UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5286057603126314049UL, 5927070171552478377UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_item_count;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___item_count => _ufle12jhs77_item_count ?? (_ufle12jhs77_item_count = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4880672858270195464UL, 2402488877140250532UL), () => _ufle12jhs77_item_count = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public FsmString name;
	public FsmInt item_count;
	public override void Reset()
	{
		name = null;
		item_count = null;
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Finish();
			return;
		}
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!item_count.IsNone)
		{
			__generatedField___item_count[as_dfa_fghsafa475_fasdfr3wetjr_index] = item_count.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's name")]
public partial class BACKPACKGetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4747402433082010641UL,7921280683061573257UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5286057603126314049UL, 5927070171552478377UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_item_count;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___item_count => _ufle12jhs77_item_count ?? (_ufle12jhs77_item_count = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4880672858270195464UL, 2402488877140250532UL), () => _ufle12jhs77_item_count = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmInt item_count;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Name=null;
		name = null;
		item_count = null;
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("BACKPACK");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=BACKPACK");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = entity.Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!item_count.IsNone)
		{
			item_count.Value = __generatedField___item_count[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's name")]
public partial class BACKPACKSetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4747402433082010641UL,7921280683061573257UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5286057603126314049UL, 5927070171552478377UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_item_count;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___item_count => _ufle12jhs77_item_count ?? (_ufle12jhs77_item_count = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4880672858270195464UL, 2402488877140250532UL), () => _ufle12jhs77_item_count = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	public FsmString name;
	public FsmInt item_count;
	public override void Reset()
	{
		_Name=null;
		name = null;
		item_count = null;
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("BACKPACK");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=BACKPACK");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, name=" + _Name.Value);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!item_count.IsNone)
		{
			__generatedField___item_count[as_dfa_fghsafa475_fasdfr3wetjr_index] = item_count.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Get the number of rows for BACKPACK meta")]
public partial class BACKPACKCount : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4747402433082010641UL,7921280683061573257UL), () => _metaDefault = null));
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entities count")]
	public FsmInt Count;
	public override void OnEnter()
	{
		if(Count != null)
		{
			Count.Value = MetaDefault.CountEntities;
		}
		Finish();
	}
	public override void Reset() => Count = null;
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Create new row")]
public partial class BACKPACKCreate : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4747402433082010641UL,7921280683061573257UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5286057603126314049UL, 5927070171552478377UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_item_count;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___item_count => _ufle12jhs77_item_count ?? (_ufle12jhs77_item_count = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4880672858270195464UL, 2402488877140250532UL), () => _ufle12jhs77_item_count = null));
	public FsmString name;
	public FsmInt item_count;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void Reset()
	{
		name = null;
		item_count = null;
	}
	public override void OnEnter()
	{
		MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(___e => {
			var as_dfa_fghsafa475_fasdfr3wetjr_index = ___e.Index;
			if(!_Index.IsNone)
			{
				_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
			}
			if(!name.IsNone)
			{
				__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
			}
			if(!item_count.IsNone)
			{
				__generatedField___item_count[as_dfa_fghsafa475_fasdfr3wetjr_index] = item_count.Value;
			}
		}));
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Delete the row by its index for BACKPACK meta")]
public partial class BACKPACKDelete : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4747402433082010641UL,7921280683061573257UL), () => _metaDefault = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		if (_Index.Value < 0)
		{
			Debug.LogWarning("Unable to delete, index is less than zero: " + _Index.Value);
			Finish();
			return;
		}
		if (_Index.Value >= MetaDefault.CountEntities)
		{
			Debug.LogWarning("Unable to delete, index is equal or greater than number of rows: " + _Index.Value +">=" + MetaDefault.CountEntities);
			Finish();
			return;
		}
		var entity = MetaDefault.GetEntity(_Index.Value);
		entity.Delete();
		Finish();
	}
	public override void Reset() => _Index = null;
}
#pragma warning restore 414
#endif
